-- MySQL Script generated by MySQL Workbench
-- 10/13/17 23:59:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idproduto` INT NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idproduto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`controle` (
  `mercadoria` VARCHAR(45) NOT NULL COMMENT '',
  `entrada` DATE NOT NULL COMMENT '',
  `saida` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`mercadoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos_has_controle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos_has_controle` (
  `produtos_idproduto` INT NOT NULL COMMENT '',
  `controle_mercadoria` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`produtos_idproduto`, `controle_mercadoria`)  COMMENT '',
  INDEX `fk_produtos_has_controle_controle1_idx` (`controle_mercadoria` ASC)  COMMENT '',
  INDEX `fk_produtos_has_controle_produtos_idx` (`produtos_idproduto` ASC)  COMMENT '',
  CONSTRAINT `fk_produtos_has_controle_produtos`
    FOREIGN KEY (`produtos_idproduto`)
    REFERENCES `mydb`.`produtos` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_has_controle_controle1`
    FOREIGN KEY (`controle_mercadoria`)
    REFERENCES `mydb`.`controle` (`mercadoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
